sudo: required

language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - SIMPLESAMLPHP_VERSION=1.17.*

before_script:
  - composer require "simplesamlphp/simplesamlphp:${SIMPLESAMLPHP_VERSION}" --no-update
  - composer update --no-interaction

script:
  - vendor/simplesamlphp/simplesamlphp-test-framework/bin/check-syntax-php.sh
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then php vendor/phpunit/phpunit/phpunit; else php vendor/phpunit/phpunit/phpunit --no-coverage; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then vendor/bin/psalm; fi

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then php vendor/bin/php-coveralls -v; fi

